name: 'Fast Webhook'
description:
  'A simple, fast-compiling Javascript Github Action to send a POST request with
  a JSON body'
branding:
  icon: 'arrow-right'
  color: 'black'
inputs:
  url:
    description: 'The webhook URL to send the request to.'
    required: true
    default: ''
  json:
    description: 'The stringified JSON body to be sent, if any.'
    required: false
    default: '{}'
runs:
  using: 'node16'
  main: 'dist/index.js'
